export enum Role {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ADMIN = 'ADMIN',
  BRANCH_MANAGER = 'BRANCH_MANAGER',
  CASHIER = 'CASHIER',
  ACCOUNTANT = 'ACCOUNTANT',
  CUSTOMER_SERVICE = 'CUSTOMER_SERVICE',
  LOAN_OFFICER = 'LOAN_OFFICER',
  ATM_MANAGER = 'ATM_MANAGER',
  AUDITOR = 'AUDITOR',
  CUSTOMER = 'CUSTOMER'
}

export enum AccountType {
  SAVINGS = 'SAVINGS',
  CURRENT = 'CURRENT',
  FIXED_DEPOSIT = 'FIXED_DEPOSIT',
  JOINT_ACCOUNT = 'JOINT_ACCOUNT',
  STUDENT = 'STUDENT',
  BUSINESS = 'BUSINESS',
  BRANCH_VAULT = 'BRANCH_VAULT',
  ATM_VAULT = 'ATM_VAULT',
  INTER_BANK_VAULT = 'INTER_BANK_VAULT',
  AGENT_BANK_VAULT = 'AGENT_BANK_VAULT',
  LOAN_VAULT = 'LOAN_VAULT'
}

export enum AccountStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  BLOCKED = 'BLOCKED',
  CLOSED = 'CLOSED',
  FREEZE = 'FREEZE',
  PENDING = 'PENDING'
}

export enum AccountCategory {
  ASSET = 'ASSET',
  LIABILITY = 'LIABILITY',
  EQUITY = 'EQUITY',
  INCOME = 'INCOME',
  EXPENSE = 'EXPENSE'
}

export enum CardType {
  DEBIT = 'DEBIT',
  CREDIT = 'CREDIT'
}

export enum CardNetwork {
  VISA = 'VISA',
  MASTERCARD = 'MASTERCARD'
}

export enum CardStatus {
  ACTIVE = 'ACTIVE',
  BLOCKED = 'BLOCKED',
  EXPIRED = 'EXPIRED',
  DISABLED = 'DISABLED',
  PENDING = 'PENDING',
  CLOSED = 'CLOSED'
}

export enum LoanStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  DISBURSED = 'DISBURSED',
  ACTIVE = 'ACTIVE',
  CLOSED = 'CLOSED',
  OVERDUE = 'OVERDUE',
  DEFAULTED = 'DEFAULTED'
}

export enum LoanType {
  PERSONAL = 'PERSONAL',
  HOME = 'HOME',
  CAR = 'CAR',
  EDUCATION = 'EDUCATION',
  BUSINESS = 'BUSINESS',
  AGRICULTURE = 'AGRICULTURE',
  GOLD = 'GOLD',
  MORTGAGE = 'MORTGAGE',
  SME = 'SME',
  OVERDRAFT = 'OVERDRAFT'
}

export enum KYCStatus {
  PENDING = 'PENDING',
  UNDER_REVIEW = 'UNDER_REVIEW',
  VERIFIED = 'VERIFIED',
  REJECTED = 'REJECTED',
  EXPIRED = 'EXPIRED'
}

export enum Gender {
  MALE = 'MALE',
  FEMALE = 'FEMALE',
  OTHER = 'OTHER'
}

export enum TransactionType {
  DEPOSIT = 'DEPOSIT',
  WITHDRAW = 'WITHDRAW',
  TRANSFER = 'TRANSFER',
  PAYMENT = 'PAYMENT',
  REFUND = 'REFUND',
  REVERSE = 'REVERSE',
  ATM_WITHDRAW = 'ATM_WITHDRAW',
  ATM_DEPOSIT = 'ATM_DEPOSIT',
  LOAN_DISBURSEMENT = 'LOAN_DISBURSEMENT',
  LOAN_REPAYMENT = 'LOAN_REPAYMENT',
  LOAN_FORECLOSURE = 'LOAN_FORECLOSURE',
  CARD_PURCHASE = 'CARD_PURCHASE',
  CARD_REVERSAL = 'CARD_REVERSAL',
  BRANCH_OPENING = 'BRANCH_OPENING',
  INTEREST_POSTING = 'INTEREST_POSTING',
  CHEQUE_ISSUE_CHARGE = 'CHEQUE_ISSUE_CHARGE',
  CARD_ISSUE_CHARGE = 'CARD_ISSUE_CHARGE',
  ATM_REFILL = 'ATM_REFILL',
  CREDIT_BILLING = 'CREDIT_BILLING',
  CREDIT_PAYMENT = 'CREDIT_PAYMENT',
  STANDING_ORDER_EXECUTION = 'STANDING_ORDER_EXECUTION'
}

export enum TransactionStatus {
  SUCCESS = 'SUCCESS',
  FAILED = 'FAILED',
  PENDING = 'PENDING',
  CANCELLED = 'CANCELLED',
  REVERSED = 'REVERSED'
}

export enum TransactionChannel {
  BRANCH = 'BRANCH',
  ATM = 'ATM',
  INTERNET_BANKING = 'INTERNET_BANKING',
  MOBILE_BANKING = 'MOBILE_BANKING',
  POS = 'POS',
  E_COMMERCE = 'E_COMMERCE',
  QR_PAYMENT = 'QR_PAYMENT',
  CARD = 'CARD',
  BEFTN = 'BEFTN',
  NPSB = 'NPSB',
  RTGS = 'RTGS',
  SWIFT = 'SWIFT',
  AGENT_BANKING = 'AGENT_BANKING',
  API = 'API',
  SYSTEM = 'SYSTEM'
}

export enum BranchType {
  HEAD_OFFICE = 'HEAD_OFFICE',
  BRANCH = 'BRANCH',
  AGENT_BANK = 'AGENT_BANK'
}

export enum BranchStatus {
  ACTIVE = 'ACTIVE',
  CLOSED = 'CLOSED'
}

export enum EmployeeStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  SUSPENDED = 'SUSPENDED',
  TERMINATED = 'TERMINATED',
  ON_LEAVE = 'ON_LEAVE'
}

export enum StandingOrderFrequency {
  DAILY = 'DAILY',
  WEEKLY = 'WEEKLY',
  BI_WEEKLY = 'BI_WEEKLY',
  MONTHLY = 'MONTHLY',
  QUARTERLY = 'QUARTERLY',
  YEARLY = 'YEARLY'
}

export enum StandingOrderStatus {
  ACTIVE = 'ACTIVE',
  PAUSED = 'PAUSED',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  FAILED = 'FAILED'
}

export enum FraudFlagStatus {
  PENDING = 'PENDING',
  REVIEWED = 'REVIEWED',
  CONFIRMED_FRAUD = 'CONFIRMED_FRAUD',
  FALSE_POSITIVE = 'FALSE_POSITIVE',
  RESOLVED = 'RESOLVED'
}

export enum FraudRiskLevel {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL'
}

export enum DocumentType {
  NID = 'NID',
  PASSPORT = 'PASSPORT',
  DRIVING_LICENSE = 'DRIVING_LICENSE',
  BIRTH_CERTIFICATE = 'BIRTH_CERTIFICATE'
}

export enum NomineeRelation {
  FATHER = 'FATHER',
  MOTHER = 'MOTHER',
  SISTER = 'SISTER',
  BROTHER = 'BROTHER',
  UNCLE = 'UNCLE',
  AUNTY = 'AUNTY',
  COUSIN = 'COUSIN',
  OTHER = 'OTHER'
}

export enum ChequeBookStatus {
  REQUESTED = 'REQUESTED',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  PRINTED = 'PRINTED',
  READY_FOR_DELIVERY = 'READY_FOR_DELIVERY',
  DELIVERED = 'DELIVERED',
  ACTIVE = 'ACTIVE',
  EXHAUSTED = 'EXHAUSTED',
  BLOCKED = 'BLOCKED',
  EXPIRED = 'EXPIRED',
  CANCELLED = 'CANCELLED'
}

export enum ChequeLeafStatus {
  UNUSED = 'UNUSED',
  ISSUED = 'ISSUED',
  PRESENTED = 'PRESENTED',
  CLEARED = 'CLEARED',
  BOUNCED = 'BOUNCED',
  STOP_PAYMENT = 'STOP_PAYMENT',
  CANCELLED = 'CANCELLED',
  EXPIRED = 'EXPIRED'
}

export enum RepaymentStatus {
  PENDING = 'PENDING',
  PAID = 'PAID',
  LATE = 'LATE',
  MISSED = 'MISSED'
}

// Mirrors com.elitetech_inc.ensarkbank.common.enums.Designation exactly (name + defaultRole).
// See DESIGNATION_LABELS / DESIGNATION_DEFAULT_ROLE in employee.models.ts for display names
// and each designation's backend-assigned default Role.
export enum Designation {
  CHIEF_EXECUTIVE_OFFICER = 'CHIEF_EXECUTIVE_OFFICER',
  MANAGING_DIRECTOR = 'MANAGING_DIRECTOR',
  DEPUTY_MANAGING_DIRECTOR = 'DEPUTY_MANAGING_DIRECTOR',
  GENERAL_MANAGER = 'GENERAL_MANAGER',
  DEPUTY_GENERAL_MANAGER = 'DEPUTY_GENERAL_MANAGER',
  ASSISTANT_GENERAL_MANAGER = 'ASSISTANT_GENERAL_MANAGER',
  BRANCH_MANAGER = 'BRANCH_MANAGER',
  ASSISTANT_BRANCH_MANAGER = 'ASSISTANT_BRANCH_MANAGER',
  OPERATIONS_MANAGER = 'OPERATIONS_MANAGER',
  TELLER = 'TELLER',
  CASH_OFFICER = 'CASH_OFFICER',
  CUSTOMER_SERVICE_OFFICER = 'CUSTOMER_SERVICE_OFFICER',
  RELATIONSHIP_MANAGER = 'RELATIONSHIP_MANAGER',
  LOAN_OFFICER = 'LOAN_OFFICER',
  ACCOUNTS_OFFICER = 'ACCOUNTS_OFFICER',
  COMPLIANCE_OFFICER = 'COMPLIANCE_OFFICER',
  AUDIT_OFFICER = 'AUDIT_OFFICER',
  SYSTEM_ADMINISTRATOR = 'SYSTEM_ADMINISTRATOR',
  SOFTWARE_ENGINEER = 'SOFTWARE_ENGINEER',
  NETWORK_ENGINEER = 'NETWORK_ENGINEER',
  DATABASE_ADMINISTRATOR = 'DATABASE_ADMINISTRATOR',
  HR_OFFICER = 'HR_OFFICER',
  ADMIN_OFFICER = 'ADMIN_OFFICER',
  FINANCE_OFFICER = 'FINANCE_OFFICER',
  TREASURY_OFFICER = 'TREASURY_OFFICER',
  SECURITY_OFFICER = 'SECURITY_OFFICER',
  OFFICE_ASSISTANT = 'OFFICE_ASSISTANT',
  INTERN = 'INTERN'
}

export enum BeneficiaryType {
  BKASH = 'BKASH',
  NAGAD = 'NAGAD',
  BANK = 'BANK',
  CARD = 'CARD',
  INTER_BANK = 'INTER_BANK'
}

export enum CustomerStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  BLOCKED = 'BLOCKED',
  PENDING = 'PENDING'
}

export enum CustomerOccupation {
  STUDENT = 'STUDENT',
  SERVICE_HOLDER = 'SERVICE_HOLDER',
  GOVERNMENT_EMPLOYEE = 'GOVERNMENT_EMPLOYEE',
  BUSINESS_OWNER = 'BUSINESS_OWNER',
  SELF_EMPLOYED = 'SELF_EMPLOYED',
  FREELANCER = 'FREELANCER',
  DOCTOR = 'DOCTOR',
  ENGINEER = 'ENGINEER',
  TEACHER = 'TEACHER',
  LAWYER = 'LAWYER',
  ACCOUNTANT = 'ACCOUNTANT',
  ARCHITECT = 'ARCHITECT',
  CONSULTANT = 'CONSULTANT',
  FARMER = 'FARMER',
  LABORER = 'LABORER',
  DRIVER = 'DRIVER',
  MECHANIC = 'MECHANIC',
  ELECTRICIAN = 'ELECTRICIAN',
  PLUMBER = 'PLUMBER',
  POLICE = 'POLICE',
  MILITARY = 'MILITARY',
  CIVIL_SERVANT = 'CIVIL_SERVANT',
  BANKER = 'BANKER',
  NGO_EMPLOYEE = 'NGO_EMPLOYEE',
  RETIRED = 'RETIRED',
  HOMEMAKER = 'HOMEMAKER',
  UNEMPLOYED = 'UNEMPLOYED',
  FOREIGN_EMPLOYEE = 'FOREIGN_EMPLOYEE',
  EXPATRIATE = 'EXPATRIATE',
  POLITICIAN = 'POLITICIAN',
  JOURNALIST = 'JOURNALIST',
  ARTIST = 'ARTIST',
  WRITER = 'WRITER',
  ACTOR = 'ACTOR',
  MUSICIAN = 'MUSICIAN',
  RELIGIOUS_LEADER = 'RELIGIOUS_LEADER',
  OTHERS = 'OTHERS'
}

export enum AddressType {
  PRESENT = 'PRESENT',
  PERMANENT = 'PERMANENT'
}

export enum Currency {
  USD = 'USD',
  EUR = 'EUR',
  GBP = 'GBP',
  BDT = 'BDT',
  INR = 'INR',
  JPY = 'JPY',
  CAD = 'CAD',
  AUD = 'AUD',
  CHF = 'CHF',
  CNY = 'CNY',
  SAR = 'SAR',
  AED = 'AED',
  SGD = 'SGD',
  MYR = 'MYR',
  THB = 'THB'
}

export enum ATMStatus {
  ACTIVE = 'ACTIVE',
  OFFLINE = 'OFFLINE',
  OUT_OF_SERVICE = 'OUT_OF_SERVICE',
  MAINTENANCE = 'MAINTENANCE'
}

export enum ATMTransactionType {
  CASH_WITHDRAW = 'CASH_WITHDRAW',
  CASH_DEPOSIT = 'CASH_DEPOSIT',
  REFILL = 'REFILL'
}

// Matches com.elitetech_inc.ensarkbank.common.enums.NotificationType exactly.
export enum NotificationType {
  TRANSACTION_SUCCESS = 'TRANSACTION_SUCCESS',
  TRANSACTION_FAILED = 'TRANSACTION_FAILED',
  DEPOSIT = 'DEPOSIT',
  WITHDRAW = 'WITHDRAW',
  TRANSFER = 'TRANSFER',
  ACCOUNT_CREATED = 'ACCOUNT_CREATED',
  ACCOUNT_SUSPENDED = 'ACCOUNT_SUSPENDED',
  ACCOUNT_STATUS_CHANGED = 'ACCOUNT_STATUS_CHANGED',
  CARD_APPLICATION = 'CARD_APPLICATION',
  CARD_STATUS_CHANGED = 'CARD_STATUS_CHANGED',
  LOAN_APPLICATION = 'LOAN_APPLICATION',
  LOAN_APPROVED = 'LOAN_APPROVED',
  LOAN_REJECTED = 'LOAN_REJECTED',
  LOAN_REPAYMENT = 'LOAN_REPAYMENT',
  KYC_SUBMITTED = 'KYC_SUBMITTED',
  KYC_VERIFIED = 'KYC_VERIFIED',
  KYC_REJECTED = 'KYC_REJECTED',
  CUSTOMER_REGISTERED = 'CUSTOMER_REGISTERED',
  INTEREST_CREDITED = 'INTEREST_CREDITED',
  CHEQUE_BOOK_REQUEST = 'CHEQUE_BOOK_REQUEST',
  CHEQUE_BOOK_APPROVED = 'CHEQUE_BOOK_APPROVED',
  CHEQUE_BOOK_REJECTED = 'CHEQUE_BOOK_REJECTED',
  CHEQUE_BOOK_DELIVERED = 'CHEQUE_BOOK_DELIVERED',
  CHEQUE_BOOK_ACTIVATED = 'CHEQUE_BOOK_ACTIVATED',
  CHEQUE_BOOK_BLOCKED = 'CHEQUE_BOOK_BLOCKED',
  GENERAL = 'GENERAL'
}

export enum HolderType {
  PRIMARY = 'PRIMARY',
  SECONDARY = 'SECONDARY',
  OPTIONAL = 'OPTIONAL',
  INTER_BANK_SETTLEMENT = 'INTER_BANK_SETTLEMENT',
  INTER_BRANCH_SETTLEMENT = 'INTER_BRANCH_SETTLEMENT'
}
