// ignore_for_file: constant_identifier_names

enum AccountType { SAVINGS, CURRENT, FIXED_DEPOSIT, JOINT_ACCOUNT, STUDENT, BUSINESS }
enum AccountStatus { ACTIVE, INACTIVE, BLOCKED, CLOSED, FREEZE, PENDING }
enum HolderType { PRIMARY, SECONDARY, OPTIONAL }
enum NomineeRelation { FATHER, MOTHER, SISTER, BROTHER, UNCLE, AUNTY, COUSIN, OTHER }

enum TransactionType { 
  DEPOSIT, 
  WITHDRAW, 
  TRANSFER, 
  PAYMENT, 
  REFUND, 
  REVERSE, 
  ATM_WITHDRAW, 
  ATM_DEPOSIT, 
  LOAN_DISBURSEMENT, 
  LOAN_REPAYMENT, 
  LOAN_FORECLOSURE, 
  CARD_PURCHASE, 
  CARD_REVERSAL, 
  BRANCH_OPENING, 
  INTEREST_POSTING, 
  CHEQUE_ISSUE_CHARGE, 
  CARD_ISSUE_CHARGE, 
  ATM_REFILL, 
  CREDIT_BILLING, 
  CREDIT_PAYMENT, 
  STANDING_ORDER_EXECUTION 
}

enum TransactionChannel { 
  BRANCH, 
  ATM, 
  INTERNET_BANKING, 
  MOBILE_BANKING, 
  POS, 
  E_COMMERCE, 
  QR_PAYMENT, 
  CARD, 
  BEFTN, 
  NPSB, 
  RTGS, 
  SWIFT, 
  AGENT_BANKING, 
  API, 
  SYSTEM 
}

enum TransactionStatus { SUCCESS, FAILED, PENDING, CANCELLED, REVERSED }

enum CardNetwork { VISA, MASTERCARD }
enum CardType { DEBIT, CREDIT }
enum CardStatus { ACTIVE, BLOCKED, EXPIRED, DISABLED, PENDING, CLOSED }

enum ChequeBookStatus { REQUESTED, APPROVED, REJECTED, PRINTED, READY_FOR_DELIVERY, DELIVERED, ACTIVE, EXHAUSTED, BLOCKED, EXPIRED, CANCELLED }
enum ChequeLeafStatus { UNUSED, ISSUED, PRESENTED, CLEARED, BOUNCED, STOP_PAYMENT, CANCELLED, EXPIRED }

enum LoanStatus { PENDING, APPROVED, REJECTED, DISBURSED, ACTIVE, CLOSED, OVERDUE, DEFAULTED }
enum RepaymentStatus { PENDING, PAID, LATE, MISSED }

enum StandingOrderFrequency { DAILY, WEEKLY, BI_WEEKLY, MONTHLY, QUARTERLY, YEARLY }
enum StandingOrderStatus { ACTIVE, PAUSED, COMPLETED, CANCELLED, FAILED }

enum BeneficiaryType { BKASH, NAGAD, BANK, CARD, INTER_BANK }
enum RequestStatus { PENDING, APPROVED, REJECTED }
enum ATMTransactionType { CASH_WITHDRAW, CASH_DEPOSIT, REFILL }

enum NotificationType { 
  TRANSACTION_SUCCESS,
  TRANSACTION_FAILED,
  DEPOSIT,
  WITHDRAW,
  TRANSFER,
  ACCOUNT_CREATED,
  ACCOUNT_SUSPENDED,
  ACCOUNT_STATUS_CHANGED,
  CARD_APPLICATION,
  CARD_STATUS_CHANGED,
  LOAN_APPLICATION,
  LOAN_APPROVED,
  LOAN_REJECTED,
  KYC_SUBMITTED,
  KYC_VERIFIED,
  KYC_REJECTED,
  CUSTOMER_REGISTERED,
  INTEREST_CREDITED,
  CHEQUE_BOOK_REQUEST,
  CHEQUE_BOOK_APPROVED,
  CHEQUE_BOOK_REJECTED,
  CHEQUE_BOOK_DELIVERED,
  CHEQUE_BOOK_ACTIVATED,
  CHEQUE_BOOK_BLOCKED,
  GENERAL
}

enum BranchType { HEAD_OFFICE, BRANCH, AGENT_BANK }
enum BranchStatus { ACTIVE, CLOSED }
enum Currency { BDT, USD, EUR, GBP }

