/**
 * Central Lucide icon registry.
 *
 * Each icon is its own standalone component with an attribute selector
 * (e.g. `svg[lucideHouse]`). Import the ones a component's template uses
 * from here (rather than reaching into '@lucide/angular' directly) so every
 * icon used app-wide is discoverable in one place.
 *
 * Usage in a component:
 *   imports: [LucideLayoutDashboard, LucideBell]
 * Usage in a template:
 *   <svg lucideLayoutDashboard class="w-5 h-5"></svg>
 */
export {
  LucideLayoutDashboard,
  LucideBuilding2,
  LucideBuilding,
  LucideUsers,
  LucideUserCheck,
  LucideUserCog,
  LucideUserPlus,
  LucideCircleUser,
  LucideCreditCard,
  LucideBanknote,
  LucideFileText,
  LucideFileCheck,
  LucideRepeat,
  LucideShieldAlert,
  LucideShieldCheck,
  LucideChartColumn,
  LucideCoins,
  LucideLandmark,
  LucideBell,
  LucideChevronDown,
  LucideChevronRight,
  LucideChevronLeft,
  LucideChevronsUpDown,
  LucideMenu,
  LucideX,
  LucideLogOut,
  LucideSearch,
  LucideListFilter,
  LucidePlus,
  LucideArrowUpRight,
  LucideArrowDownRight,
  LucideArrowLeft,
  LucideArrowRight,
  LucideTrendingUp,
  LucideTrendingDown,
  LucideWallet,
  LucideArrowLeftRight,
  LucideReceipt,
  LucidePiggyBank,
  LucideScrollText,
  LucideHandCoins,
  LucideHandshake,
  LucideCalendarClock,
  LucideEye,
  LucideEyeOff,
  LucideDownload,
  LucideUpload,
  LucideLock,
  LucideLockOpen,
  LucideCheck,
  LucidePencil,
  LucideTrash2,
  LucideEllipsisVertical,
  LucideEllipsis,
  LucideRefreshCw,
  LucideTriangleAlert,
  LucideCircleCheck,
  LucideCircleX,
  LucideCircleAlert,
  LucideClock,
  LucideInfo,
  LucideMapPin,
  LucidePhone,
  LucideMail,
  LucideCircleDollarSign,
  LucideQrCode,
  LucideSmartphone,
  LucideGlobe,
  LucideSlidersHorizontal,
  LucideLoaderCircle,
  LucideBan,
  LucideKeyRound,
  LucideSettings,
  LucideHouse,
  LucideFunnel,
  LucideBadgeCheck,
  LucideLayoutGrid,
  LucidePanelLeftClose,
  LucidePanelLeftOpen,
  LucideImage,
  LucideIdCard,
  LucideSignature,
  LucideCamera,
} from '@lucide/angular';
